### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by DeSfeerhaard** [paynl/prestashop1.7-plugin#1]
When i upload the plugin with PrestaShop, it will automatically install for me. But the installation never finishes.. So no succes. Prestashop and everything in it, is up to date. My upload speed is lightning fast and i never had this issue (more then 100 modules installed). Any suggestions on how to solve this issue?

**Comment by DeSfeerhaard** [comment]
? :)

**Comment by andypieters** [comment]
Did you install the package and not the source code?
https://github.com/paynl/prestashop1.7-plugin/releases/download/v4.2.0/paynlpaymentmethods-v4.2.0.zip
This is the file you should upload

**Comment by DeSfeerhaard** [comment]
I tried every zip file

**Comment by jot1976** [comment]
.Do you perhaps know what is the problem when I copy the extracted module folder via ftp into the modules folder on my website, but do not see the module listed in the dashboard under installed modules? I am running prestashop 1.7.2

**Comment by DeSfeerhaard** [comment]
??
