### ISSUE TITLE
PS 1.7.7.2  broken order info - duplicate payment confirmation - with operation time out.

### ISSUE THREAD

**Issue by Peter4661** [paynl/prestashop1.7-plugin#32]
With payment operation times out, 

!  payment information is duplicated in the order information.
!! payment information is incorrect shown in order ( as customer payed order multiple times)
!!! packing list and / or  invoice does not show items ordered.

[DE021954 (1).pdf](https://github.com/paynl/prestashop1.7-plugin/files/6107565/DE021954.1.pdf)
![screenshot_20210309_104200](https://user-images.githubusercontent.com/11147327/110451796-daef6700-80c4-11eb-8298-1607a022b69f.jpg)
![screenshot_20210309_104308](https://user-images.githubusercontent.com/11147327/110451835-e3e03880-80c4-11eb-9ac0-4c8c828f8f03.jpg)
![screenshot_20210309_104053](https://user-images.githubusercontent.com/11147327/110451864-eb9fdd00-80c4-11eb-8823-8cb32ebf66c7.jpg)

**Comment by woutse** [comment]
Could you please send this issue to support@pay.nl ?
