### ISSUE TITLE
Internal server error 

### ISSUE THREAD

**Issue by rkooi-tsupport** [paynl/prestashop1.7-plugin#42]
Bij versie 4.3 krijg ik in PS 1.7.6.5 een Internal Server Error als ik de module wil configureren of als de klant wil inloggen om zijn winkelmand af te rekenen.

**Comment by woutse** [comment]
Bedankt voor je bericht, we gaan het onderzoeken en komen hier zsm op terug.

**Comment by woutse** [comment]
We hebben de installatie zip-file, die bij de release is inbegrepen, aangepast. Ik verwacht dat daarmee het probleem is opgelost. Kun je dat bevestigen?

**Comment by rkooi-tsupport** [comment]
Het ligt vast aan mijn onervarenheid met Github maar ik kan de nieuwe zip-file niet vinden.

**Comment by woutse** [comment]
Het gaat om deze file:
https://github.com/paynl/prestashop1.7-plugin/releases/download/v4.3.0/paynlpaymentmethods_4.3.0.zip

**Comment by rkooi-tsupport** [comment]
Dank, alles is gelukt.
