### ISSUE TITLE
Shoppingcart not completely transferred to order.

### ISSUE THREAD

**Issue by venditdevs** [paynl/prestashop1.7-plugin#45]
We've encountered the exact same problem with two (maybe three) customers. All on Prestashop 1.7.8.2 and module version 4.3.0.

We don't know what happends, the fact is that the carrier, products, orderstatus and payment are not allways booked/trasferred on/to the order but are present in the shoppingcart. If we look in the serverlogs we don't see anything unusual.

Shopping Cart:
![image](https://user-images.githubusercontent.com/14218917/149098567-cd7b11e9-fefa-4945-b199-16c524c61964.png)

![image](https://user-images.githubusercontent.com/14218917/149098812-4fdbeb5e-669d-4759-9c37-3357091e77c5.png)

Order products and carrier:
![image](https://user-images.githubusercontent.com/14218917/149097805-dc7aac25-ae7d-4b74-b53a-5dc72f5ab8ed.png)

Order status:
![image](https://user-images.githubusercontent.com/14218917/149098136-b92722fd-780d-4853-810b-b7a88327448e.png)

Order payment:
![image](https://user-images.githubusercontent.com/14218917/149097906-c176e709-b5e9-4b56-93b2-06b0cb266fb9.png)

Example 2:
Products missing:
![image](https://user-images.githubusercontent.com/14218917/149101700-91225006-7d75-44d1-99ab-395e12304d77.png)

including payment method but no carrier
![image](https://user-images.githubusercontent.com/14218917/149102192-ac76de3d-025e-4bda-bb97-9d11c2b45f95.png)

The second shop has Pay logging active, these are the corresponding records, i can provide the ID's through e-mail if needed:
![image](https://user-images.githubusercontent.com/14218917/149105463-638c62ff-67b1-4ecc-b519-513d98a779a7.png)

**Comment by woutse** [comment]
Thanks for your message. We're looking into it.

**Comment by woutse** [comment]
Could you please e-mail the corresponding pay-orderId to support@pay.nl?
