### ISSUE TITLE
Code typo line 728 file paynlpaymentmethods.php

### ISSUE THREAD

**Issue by HunkBenny** [paynl/prestashop1.7-plugin#46]
I believe to have found an if-statement that will never be true.

Line 728 contains the same conditional as line 725.
But line 726 makes it so this conditional is never considered true.

https://github.com/paynl/prestashop1.7-plugin/blob/e4c236495a6eed7dfabf826947ee9fdd2ba3f83b/paynlpaymentmethods/paynlpaymentmethods.php#L725-L730

**Comment by woutse** [comment]
Thanks for your message. We'll look into it!

**Comment by woutse** [comment]
Resolved in version 4.6.0
