### ISSUE TITLE
Error: PAY-405 - Parameter 'productId' is invalid: Input is too long, maximum length is 25

### ISSUE THREAD

**Issue by AaronTajriba** [paynl/prestashop1.7-plugin#47]
I've upgrade a shop to the 4.5.1 version of the PAYnl module, the shop itself is running prestashop 1.7.7.8. With normal transactions the module is working just fine. But when you try to checkout with a cartrule using a discount code like demoshop_EFLRV8QWH7P2DAGJZM5C you get the following Error:

`Error: PAY-405 - Parameter 'productId' is invalid: Input is too long, maximum length is 25`

This was not the case in the previous module version(4.3.0) running in this shop.

**Comment by woutse** [comment]
Thanks for your message, we'll look into it!

**Comment by woutse** [comment]
Resolved in 4.6.0!
