### ISSUE TITLE
Not possible to configure the module after a clean 4.6.0 install.

### ISSUE THREAD

**Issue by venditdevs** [paynl/prestashop1.7-plugin#48]
It's not possible to configure the 4.6.0 version module after a clean install on (in this case) Prestashop 1.7.8.6. See screenshot.

![image](https://user-images.githubusercontent.com/14218917/179929439-c5dd0c9f-a316-4b66-a090-8cd4893dfa70.png)

**Comment by woutse** [comment]
Thanks for your reply. Glad to hear it worked now. So for now we will consider this issue solved - but we'll keep this in mind! Thanks again for reporting.
