### ISSUE TITLE
Possibility to add Country of customer in "Transactieomschrijving voorvoegsel"

### ISSUE THREAD

**Issue by basemedia** [paynl/prestashop1.7-plugin#50]
We would like to suggest an improvement:
Possibility to add Country of customer in "Transactieomschrijving voorvoegsel"

It's possible to add a prefix in front of the cart-id. We would like to add the country and if possible customer name.

Prestashop: 1.7
module: 4.8.0

**Comment by basemedia** [comment]
Or maybe add the country of customer in extra2 or extra3 field.

**Comment by escruickshank** [comment]
Hi! Thank you for your suggestion. What would you like to use this for? 
In My.pay you can already easily filter your orders based on the delivery address (including country).

**Comment by basemedia** [comment]
Would be great if we have this in the Specification clearing zip (csv transaction file). We use this information for the VAT.

**Comment by escruickshank** [comment]
Good morning! We have a sync module available where you can add your own filters and select your own file type (like csv) to export transaction details. You can view this by going to [My Pay. ](https://my.pay.nl/)-> Merchant -> Sync & Tasks. If you need any help, my colleagues at support@pay.nl can help you further.

**Comment by basemedia** [comment]
We are using this function. But the information in the sync is based on the IP location of the customer. We need the information of the delivery address.

**Comment by woutse** [comment]
Could you please send your request to support@pay.nl? They can tell you if the desired information is already available or if a plugin update is needed. Then for now  i will close this ticket.
