### ISSUE TITLE
Calculatie Prestashop 5 cijfers achter de komma

### ISSUE THREAD

**Issue by basemedia** [paynl/prestashop1.7-plugin#51]
Als we in Prestashop 5 cijfers achter de komma instellen(dit is gewenst om de juiste btw calculatie te krijgen bij grote bestellingen) verwerkt de Pay module de betaling af en toe niet goed (status probleem met betaling) 

De oorzaak ligt(voor zover wij kunnen zien) in de tabel ps_pay_transactions - amount op het moment dat er meet dan 2 cijfers achter de komma staan dan kan de Pay module de bestelling niet goed afronden. Wellicht komt het bedrag dan niet overeen met wat Pay verwacht?

De afronding is in te stellen onder Winkelinstellen -> Algemeen
<img width="422" alt="tabel-ps-pay-transactions" src="https://user-images.githubusercontent.com/1645341/209095638-4718c203-4c67-4d76-9432-b4648953bc85.png">
<img width="966" alt="afronding-5" src="https://user-images.githubusercontent.com/1645341/209095671-07299e0b-518e-4b33-957a-6478982a4d89.png">

**Comment by escruickshank** [comment]
Hi! Wij hebben hiernaar gekeken en kunnen dit niet reproduceren. Zouden jullie de logs willen doorsturen naar support@pay.nl van een transactie waarbij dit fout gaat? Dan onderzoeken we via daar verder. Het issue hier sluit ik.
