### ISSUE TITLE
Issue B2B (EX VAT) transactions

### ISSUE THREAD

**Issue by HunkBenny** [paynl/prestashop1.7-plugin#52]
This could be an issue that only we have, due to a large number of different modules in our webshop. However, it seems as if when a customer outside of the EEA or a business (with VAT-number) within the EEA place an order, it is not validated correctly. 

The orderstate is not updated in the Backoffice (it receives the 'Error'-orderstate). This is, due to the fact that the $amountPaid variable is equal to 'null' in such a situation. 

https://github.com/paynl/prestashop1.7-plugin/blob/a6c1378119b11ea3443640e7b0398c1391a1e23f/paynlpaymentmethods/paynlpaymentmethods.php#L713-L720

Changing line 718-719 to the following resolved our issue:

```
if (is_null($amountPaid)) {
    $amountPaid = in_array(round($cart->getOrderTotal(), 2), $arrPayAmounts) ? $cart->getOrderTotal() : $cart->getOrderTotal(false);
```

This is an issue that we also had in june of this year. However I forgot to create an issue on it as I thought it was something only we witnessed. The solution that I propose does not break the current code in other scenarios I believe. It only helps others in the same situation as us.

### Little bit of explanation 

`$cart->getOrderTotal()`
This defaults to taking the total of the cart with taxes! It has a keyword argument '$withTaxes' that defaults to 'true'.

`$cart->getOrderTotal(false)`
This changes the keyword argument, so we allow for $amountPaid to become without VAT.

This usecase is important for B2B transactions inside of the EEA & every transaction outside of the EEA.

Best of wishes for 2023!
Benny

**Comment by woutse** [comment]
Thanks for your message, we'll look into this!  And best of wishes for you too!

**Comment by HunkBenny** [comment]
I saw you implemented this in your release of three weeks ago. Thanks!

Closing this issue :)
